format = '$directory$character'
right_format = '$all'

# Inserts a blank line between shell prompts
add_newline = true

[nodejs]
disabled = true

[package]
disabled = true

[cmd_duration]
disabled = true

