theme = "molokai"
   
[editor]
end-of-line-diagnostics = "hint"

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

[editor.inline-diagnostics]
cursor-line = "error"
# other-lines = "error"

[editor.indent-guides]
render = true

[editor.statusline]
center = ["file-type"]

[editor.whitespace.render]
space = "none"
tab = "all"
nbsp = "all"
nnbsp = "all"
newline = "none"

[editor.whitespace.characters]
space = "·"
nbsp = "⍽"
nnbsp = "␣"
tab = "→"
newline = "⏎"
# tabpad = "·"

# create a new minor mode bound to `+`
[keys.normal."+"]
m = ":run-shell-command echo 2"
c = ":run-shell-command cargo build"
t = ":run-shell-command cargo test"
n = ":run-shell-command echo 3"

# [keys.normal.y]
# y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "normal_mode", "collapse_selection"]

[keys.normal.m]
e = "expand_selection"

